### PR TITLE
Update package.json for 0.7

### PR DESCRIPTION
**Pull request by denolfe**
Updated package.json for 0.7. No longer errors out when starting up NodeCG

### CODE REVIEW

**Comment by coolacid** [comment]
There is a bug with this PR - it will not run on a clean install. 

There is a fork here ( https://github.com/tmtrademark/bubu-followers/commit/5bf57bc621bc8cba9abd76af6e0704a33ba986e8 ) that might hint at requirements. Adding the extra bundleDependencies at least tells you if a missing bundle is there.

**Comment by denolfe** [comment]
Yeah, that appears to be what I'm missing. I'll take a look tonight.

**Comment by denolfe** [comment]
@coolacid This depends on lfg-twitchapi, which unfortunately has not been updated for 0.7 either :(

**Comment by coolacid** [comment]
\o/ More PRs to update all the things. :speak_no_evil:

**Comment by coolacid** [comment]
@denolfe It's been updated.

**Comment by eaceaser** [comment]
lol sorry i totally did not see this PR. I think lfg-twitchapi just got updated to 0.7 (i saw a notification somewhere).

**Comment by denolfe** [comment]
Welp, I can't get my twitch login auth to work to test my changes. 

Thoughts on removing the lfg-twitchapi dependency in general? Considering, it doesn't perform any API calls that would need to auth with twitch anyway.

**Comment by coolacid** [comment]
+1 for removing lfg-twitchapi I found it cumbersome.

**Comment by denolfe** [comment]
@eaceaser This should be good to go. Let me know if anything is wonky. My WebStorm freaks out on the ES6 stuff.

**Comment by denolfe** [comment]
@coolacid Let me know if you see anything else

**Comment by eaceaser** [comment]
lgtm. @denolfe lmk if its ready to merge

**Comment by coolacid** [comment]
Looks awesome to my poor eyes ;)

**Comment by denolfe** [comment]
@eaceaser Go for it!

**Pull request merged**
